# Generated by Django 4.1 on 2022-08-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0003_usersregistered_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersregistered',
            name='image',
            field=models.ImageField(blank=True, null='True', upload_to='userimage'),
        ),
    ]
