# Generated by Django 4.1 on 2022-08-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0005_alter_usersregistered_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersregistered',
            name='image',
            field=models.ImageField(blank=True, default='/static/images/user.png', null=True, upload_to='userimage'),
        ),
    ]
