# Generated by Django 4.1 on 2022-08-29 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0006_alter_usersregistered_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersregistered',
            name='image',
        ),
    ]
