# Generated by Django 4.1 on 2022-08-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0007_remove_usersregistered_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blogimages')),
                ('title', models.CharField(max_length=255)),
                ('small_desc', models.CharField(max_length=500)),
                ('main_content', models.CharField(max_length=4000)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
