# Generated by Django 4.1 on 2022-08-29 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0008_blogdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogdata',
            old_name='main_content',
            new_name='maincontent',
        ),
        migrations.RenameField(
            model_name='blogdata',
            old_name='small_desc',
            new_name='smalldesc',
        ),
    ]
