# Generated by Django 4.1 on 2022-08-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0009_rename_main_content_blogdata_maincontent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdata',
            name='image',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='blogimages'),
        ),
    ]
