# Generated by Django 4.1 on 2022-08-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0010_alter_blogdata_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdata',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blogimages'),
        ),
        migrations.AlterField(
            model_name='blogdata',
            name='maincontent',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='blogdata',
            name='smalldesc',
            field=models.CharField(max_length=255),
        ),
    ]
