# Generated by Django 4.1 on 2022-08-31 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0012_alter_blogdata_maincontent_alter_blogdata_smalldesc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersRegistered',
        ),
    ]
