# Generated by Django 4.1 on 2022-09-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0014_usersregistered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersregistered',
            name='occupation',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='usersregistered',
            name='summary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
