# Generated by Django 4.1 on 2022-09-02 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0015_alter_usersregistered_occupation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogData',
        ),
    ]
