# Generated by Django 4.1 on 2022-09-02 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0017_blogdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogData',
        ),
    ]
