# Generated by Django 4.1 on 2022-09-02 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0018_delete_blogdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blogimages')),
                ('title', models.CharField(max_length=255)),
                ('smalldesc', models.CharField(max_length=500)),
                ('maincontent', models.CharField(max_length=4000)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('authorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogApp.usersregistered')),
            ],
        ),
    ]
